---
- name: Pentesters Server Configuration
  hosts: pentest_server
  become: true
  vars:
    pentest_tools:
      - metasploit-framework
      - nmap
      - burpsuite_community_v2020.1.jar
      - sqlmap
      - hydra
      - aircrack-ng
      - wireshark
      # Add other pentest tools here

  tasks:
    - name: Install pentest tools
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ pentest_tools }}"

    - name: Read usernames from users.txt file
      ansible.builtin.slurp:
        src: users_pentester.txt # replaced with the file containing the users_pentester
      register: user_list

    - name: Create users from users.txt file
      ansible.builtin.user:
        name: "{{ item }}"
        password: "xxxxxx"
        shell: /bin/bash
        groups: pentesters
        append: yes
      loop: "{{ user_list['content'] | b64decode | split('\n') | select('string') }}"

    - name: Limit access to sudo
      copy:
        dest: /etc/sudoers.d/pentesters
        content: "%pentesters ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
